"""empty message

Revision ID: 0674fc915882
Revises: None
Create Date: 2017-01-22 19:04:01.087712

"""

# revision identifiers, used by Alembic.
revision = '0674fc915882'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('abreviation', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('product',
    sa.Column('production_time', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('current_selling_price', sa.Integer(), nullable=True),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['brand.name'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('produce',
    sa.Column('product', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_needs',
    sa.Column('product_out', sa.String(length=30), nullable=False),
    sa.Column('product_in', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_in'], ['product.code'], ),
    sa.ForeignKeyConstraint(['product_out'], ['product.code'], ),
    sa.PrimaryKeyConstraint('product_out', 'product_in')
    )
    op.create_table('purchase',
    sa.Column('product', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('action_date', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('product', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('action_date', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('purchase')
    op.drop_table('production_needs')
    op.drop_table('produce')
    op.drop_table('product')
    op.drop_table('brand')
    # ### end Alembic commands ###
