"""empty message

Revision ID: 0748cd240931
Revises: None
Create Date: 2017-01-29 18:30:32.102239

"""

# revision identifiers, used by Alembic.
revision = '0748cd240931'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('supplier',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('product',
    sa.Column('production_time', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('type_', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('current_selling_price', sa.Integer(), nullable=True),
    sa.Column('current_quantity', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['brand.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('production',
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.Integer(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('production_needs',
    sa.Column('product_out', sa.Integer(), nullable=False),
    sa.Column('product_in', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_in'], ['product.id_'], ),
    sa.ForeignKeyConstraint(['product_out'], ['product.id_'], ),
    sa.PrimaryKeyConstraint('product_out', 'product_in')
    )
    op.create_table('purchase',
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('action_date', sa.Integer(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id_'], ),
    sa.ForeignKeyConstraint(['supplier'], ['supplier.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('sale',
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('action_date', sa.Integer(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('purchase')
    op.drop_table('production_needs')
    op.drop_table('production')
    op.drop_table('product')
    op.drop_table('supplier')
    op.drop_table('brand')
    # ### end Alembic commands ###
