"""empty message

Revision ID: 25743fc519b2
Revises: 019bfb836074
Create Date: 2017-01-29 20:59:50.405191

"""

# revision identifiers, used by Alembic.
revision = '25743fc519b2'
down_revision = '019bfb836074'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('supplier', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'brand', 'supplier', ['supplier'], ['id_'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.drop_column('brand', 'supplier')
    # ### end Alembic commands ###
