"""empty message

Revision ID: 40fbda89af2a
Revises: d4f2e4ef5b1e
Create Date: 2017-09-03 17:37:54.127843

"""

# revision identifiers, used by Alembic.
revision = '40fbda89af2a'
down_revision = 'd4f2e4ef5b1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('supplier', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'image')
    op.drop_column('brand', 'image')
    # ### end Alembic commands ###
