"""empty message

Revision ID: 4c6632617022
Revises: f719fe7c700a
Create Date: 2017-02-15 22:00:21.421420

"""

# revision identifiers, used by Alembic.
revision = '4c6632617022'
down_revision = 'f719fe7c700a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_needs', 'product',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production_needs', 'product_in',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_needs', 'product_in',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_needs', 'product',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
