"""empty message

Revision ID: 4c8b104618bb
Revises: 210df5b14893
Create Date: 2017-01-22 23:29:27.980597

"""

# revision identifiers, used by Alembic.
revision = '4c8b104618bb'
down_revision = '210df5b14893'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('abbreviation', sa.String(length=10), nullable=True))
    op.add_column('brand', sa.Column('id_', sa.Integer(), nullable=True))
    op.drop_column('brand', 'id')
    op.drop_column('brand', 'abreviation')
    op.add_column('produce', sa.Column('id_', sa.Integer(), nullable=False))
    op.drop_column('produce', 'id')
    op.add_column('product', sa.Column('id_', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('type_', sa.String(length=30), nullable=True))
    op.drop_column('product', 'type')
    op.drop_column('product', 'id')
    op.add_column('production_needs', sa.Column('id_', sa.Integer(), nullable=True))
    op.drop_column('production_needs', 'id')
    op.add_column('purchase', sa.Column('id_', sa.Integer(), nullable=False))
    op.drop_column('purchase', 'id')
    op.add_column('sale', sa.Column('id_', sa.Integer(), nullable=False))
    op.drop_column('sale', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('sale', 'id_')
    op.add_column('purchase', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('purchase', 'id_')
    op.add_column('production_needs', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('production_needs', 'id_')
    op.add_column('product', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('product', 'type_')
    op.drop_column('product', 'id_')
    op.add_column('produce', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('produce', 'id_')
    op.add_column('brand', sa.Column('abreviation', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('brand', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('brand', 'id_')
    op.drop_column('brand', 'abbreviation')
    # ### end Alembic commands ###
