"""empty message

Revision ID: b5d826fbeb95
Revises: 25743fc519b2
Create Date: 2017-01-29 22:50:26.051735

"""

# revision identifiers, used by Alembic.
revision = 'b5d826fbeb95'
down_revision = '25743fc519b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('brand', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['brand.id_'], ),
    sa.ForeignKeyConstraint(['supplier'], ['supplier.id_'], )
    )
    op.drop_constraint('brand_supplier_fkey', 'brand', type_='foreignkey')
    op.drop_column('brand', 'supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('supplier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('brand_supplier_fkey', 'brand', 'supplier', ['supplier'], ['id_'])
    op.drop_table('association')
    # ### end Alembic commands ###
