"""empty message

Revision ID: b8fa640ec739
Revises: b5d826fbeb95
Create Date: 2017-01-30 20:42:51.647997

"""

# revision identifiers, used by Alembic.
revision = 'b8fa640ec739'
down_revision = 'b5d826fbeb95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_needs', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_needs', 'comment')
    # ### end Alembic commands ###
